apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.componentName }}
spec:
  host: {{ .Values.componentName }}
  subsets:
  {{ range $i, $var := .Values.appEntries -}}
  - name: {{ $var.circleId  }}
    labels:
      circleId: {{ $var.circleId }}
      component: {{ $var.componentName }}
      tag: {{ $var.imageTag }}
  {{ end }}
  - name: {{ .Values.defaultVersion.circleId}}
    labels:
      circleId: {{ .Values.defaultVersion.circleId }}
      component: {{ .Values.defaultVersion.componentName }}
      tag: {{ .Values.defaultVersion.imageTag }}
