apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.componentName }}
spec:
  {{ if .Values.virtualGateway }}
  gateways:
  - {{ .Values.virtualGateway }}
  {{ end }}
  hosts:
  - {{ .Values.hostName }}
  http:
  {{ range $i, $var := .Values.appEntries -}}
  - match:
    - headers:
        x-circle-id:
            exact: {{ $var.circleId}}
    route:
    - destination:
        host: {{ $var.componentName }}
        subset: {{ $var.circleId }}
      headers:
        request:
          set:
            x-circle-source: {{ $var.circleId }}
        response:
          set:
            x-circle-source: {{ $var.circleId }}
  - match:
    - headers:
        cookie:
          regex: .*x-circle-id={{ $var.circleId}}.*
    route:
    - destination:
        host: {{ $var.componentName }}
        subset: {{ $var.circleId }}
      headers:
        request:
          set:
            x-circle-source: {{ $var.circleId }}
        response:
          set:
            x-circle-source: {{ $var.circleId }}
  {{ end }}
  - route:
    - destination:
        host: {{ .Values.componentName }}
        subset: {{ .Values.defaultVersion.circleId }}
      headers:
        request:
          set:
            x-circle-source: {{ .Values.defaultVersion.circleId }}
        response:
          set:
            x-circle-source: {{ .Values.defaultVersion.circleId }}
