apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}
spec:
  hosts:
  - {{ .Values.appName }}
  http:
  {{ range $i, $var := .Values.appEntries -}}
  - match:
    - headers:
        x-circle-id:
            exact: {{ $var.circleId}}
    route:
    - destination:
        host: {{ $.Values.appName }}
        subset: {{ $var.value }}
  {{ end }}
  - route:
    - destination:
        host: {{ .Values.appName }}
        subset: {{ .Values.defaultVersion.value }}
