apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  labels:
    app: {{ .Values.component }}
    version: {{.Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.component }}
      version: {{.Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
        version: {{.Values.version }}
    spec:
      containers:
      - name: {{ .Values.component }}
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: {{ .Values.version }} 