apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-custom-{{ .Values.version }}
  labels:
    app: hello-kubernetes-custom-{{ .Values.version }}
    version: {{.Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-custom-{{ .Values.version }}
      version: {{.Values.version }}
  template:
    metadata:
      labels:
        app: hello-kubernetes-custom-{{ .Values.version }}
        version: {{.Values.version }}
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: {{ .Values.version }} 