# hello-kubernetes.custom-message.yaml
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.component }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app:  {{ .Values.component }}